// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi A Todo list application
A tutorial for the Gophers in Linz


    Schemes:
      http
    Host: localhost
    BasePath: /v1
    Version: 1.0.0

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
